### ISSUE TITLE
Clean UP & Dockerization eos4se9

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos4se9#3]

**Comment by simrantan** [comment]
I've run into a bug when trying to fetch the model locally (clone and fetch with --repo_path). Though the workflows all pass, on my device, I get this error: `
--- Logging error in Loguru Handler #4 ---
Record was: {'elapsed': datetime.timedelta(seconds=78, microseconds=556481), 'exception': None, 'extra': {}, 'file': (name='logging.py', path='/home/simran/ersilia/ersilia/utils/logging.py'), 'function': 'debug', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 68, 'message': 'Activation done', 'module': 'logging', 'name': 'ersilia.utils.logging', 'process': (id=2778, name='MainProcess'), 'thread': (id=139658138329728, name='MainThread'), 'time': datetime(2023, 6, 30, 11, 18, 54, 899098, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200), 'PDT'))}
Traceback (most recent call last):
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_handler.py", line 177, in emit
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_file_sink.py", line 172, in write
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_file_sink.py", line 104, in rotation_size
OSError: [Errno 30] Read-only file system
--- End of logging error ---
11:18:54 | DEBUG    | Activation done
--- Logging error in Loguru Handler #4 ---
Record was: {'elapsed': datetime.timedelta(seconds=78, microseconds=557224), 'exception': None, 'extra': {}, 'file': (name='logging.py', path='/home/simran/ersilia/ersilia/utils/logging.py'), 'function': 'debug', 'level': (name='DEBUG', no=10, icon='🐞'), 'line': 68, 'message': 'Creating environment YAML file', 'module': 'logging', 'name': 'ersilia.utils.logging', 'process': (id=2778, name='MainProcess'), 'thread': (id=139658138329728, name='MainThread'), 'time': datetime(2023, 6, 30, 11, 18, 54, 899841, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=61200), 'PDT'))}
Traceback (most recent call last):
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_handler.py", line 177, in emit
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_file_sink.py", line 172, in write
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_file_sink.py", line 104, in rotation_size
OSError: [Errno 30] Read-only file system
--- End of logging error ---
11:18:54 | DEBUG    | Creating environment YAML file
🚨🚨🚨 Something went wrong with Ersilia 🚨🚨🚨

Error message:

[Errno 30] Read-only file system: '/tmp/ersilia-0b9snf10'
If this error message is not helpful, open an issue at:
 - https://github.com/ersilia-os/ersilia
Or feel free to reach out to us at:
 - hello[at]ersilia.io

If you haven't, try to run your command in verbose mode (-v in the CLI)
 - You will find the console log file in: /home/simran/eos/current.log
 38%|███████████████████████████████▉                                                     | 3/8 [01:16<02:08, 25.65s/it]
Exception ignored in atexit callback: <bound method Logger.remove of <loguru.logger handlers=[(id=5, level=10, sink=<stderr>)]>>
Traceback (most recent call last):
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_logger.py", line 1016, in remove
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_handler.py", line 195, in stop
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_file_sink.py", line 228, in stop
  File "/home/simran/miniconda3/envs/ersilia/lib/python3.10/site-packages/loguru/_file_sink.py", line 193, in _terminate_file
OSError: [Errno 30] Read-only file system`
It seems to maybe be an error with my operating system? I am working on debugging and looking up whats going on but wanted to write it up here in case this has been seen before

**Comment by simrantan** [comment]
I looked into this more and have found this is an issue with my laptop - I am working on resolving it as all of my applications are currently failing.

**Comment by simrantan** [comment]
I've finally resolved the issue on my laptop and will start on refactoring, the model itself is actually fine it was my computer's fault the whole time.

**Comment by GemmaTuron** [comment]
Hi @simrantan ,

Cool good to hear you've been able to resolve this!

**Comment by simrantan** [comment]
I have finished refactoring the model and am now testing it locally! I have run into some endless running issues(it never returns a result for any input SMILE, ran for 3 hours in the background without returning an output), so I am working on debugging that infinite run error before submitting a PR.

**Comment by simrantan** [comment]
I got it working! Testing multiple inputs to see if it works on larger files

**Comment by simrantan** [comment]
As of now, the model works on small or single inputs, but has been running in the background for a little over 2 hours on eml_canonical - I am unsure why it is taking so long. I am planning to test the original version locally to see how long it takes to run eml_canonical and determine if this is an issue in the model itself or one caused by refactoring.

**Comment by GemmaTuron** [comment]
Hi @simrantan 

It could be the model is slow simply, how long did it take to calculate a file of 20 smiles for example? Also, did you test the model is accepting input and output in .csv format before passing the whole file?

**Comment by simrantan** [comment]
Let me check! from my testing so far, it takes approximately 1.5 minutes to calculate a file of 1 smile and it does accept input and output files in csv format.

**Comment by simrantan** [comment]
I ran a file of 20 smiles and it took about 12 minutes to run - I am trying eml_canonical once more to see if it can complete running at some point today

**Comment by simrantan** [comment]
I added a print statement in the for loop in main.py but it is not printing to terminal, even for single inputs, so I am looking into what I may have done incorrectly in implementing this - I am searching online resources for help but will put the code I changed here in case anyone has any advice! 
My change: 
`def my_model(smiles_list):
    for smi in smiles_list:
        print(smi)
        translate_forward(smi)
    return 
`
Original: 
`def my_model(smiles_list):
    return [translate_forward(smi) for smi in smiles_list]
`

**Comment by GemmaTuron** [comment]
Did you re-fetch the model? or run it directly from bash.sh? that might be the issue. Once a model is fetched if you serve it from Ersilia it will use whatever code was there at the moment of fetching, not new one

**Comment by simrantan** [comment]
I did re-fetch the model and try running - I think the change causes the model to not work since a one-smile size file now doesn't return. I have also tried running bash, which is giving me various module missing errors (i attempted to resolve them and ended up needing to reset my conda environment back to the base ersilia since it created numerous package dependency issues). 
I am attempting again with a different print method to see if it will work better!

**Comment by simrantan** [comment]
I found that the code I originally wrote to print was causing an error in processing the smiles, so I spent some time testing different ways of printing and eventually, after some fiddling around I got it to work! It looks like the model is working perfectly fine, it just takes a very, very long time for eml_canonical to complete because the model is slow. Submitting a PR!

**Comment by GemmaTuron** [comment]
@simrantan  Can you show the code here in case anyone else wants to use it?

**Comment by GemmaTuron** [comment]
@simrantan I leave this issue open so you can show the code you used to print the smiles progress

**Comment by simrantan** [comment]
Oh sorry I missed the previous message! Thank you for bumping it!

This is the code I used:
`with open(input_file, "r") as f:
    reader = csv.reader(f)
    next(reader) # skip header
    smiles_list = [r[0] for r in reader]

print("hello")

# run model
iupacs_names = my_model(smiles_list)

# write output in a .csv file
with open(output_file, "w") as f:`

I added a print statement after the file is read but before the processing occurs, since I kept having issues a print statement in the my_model function as it affected the functionality. I used this since it told me if the input file had been read successfully, which was all I needed to know for my testing purposes.

**Comment by GemmaTuron** [comment]
thanks @simrantan !

@pittmanriley I know you were doing something similar for other models, tagging you here so you can see it
